#!/usr/bin/env bash
#
# bootstrap installs things.
source ./script/prompt

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setting up gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    bot ' - What is your github author name?'
    read -e git_authorname
    bot ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    ok 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        bot "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      ok "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      ok "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      ok "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    ok "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

add_cron () {
  local frequency="*/15 * * * *"
  local command=$1
  local job="$frequency $command"
  cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
}

add_line () {
  local command=$1
  local job="$command"
  cat <(fgrep -i -v "$command" <(crontab -l)) <(echo "$job") | crontab -
}



installMods () {
  info "starting aaroncoville's mods"
  #backup old bin, if exists
  if [ -d $HOME/bin ]; then
    info "current $HOME/bin folder, checking for existing symlink"
    if [ ! -L $HOME/bin ]; then
      info "current $HOME/bin is not a symlink, creating backup"
      sudo mv $HOME/bin bin_old
      ok "backup folder created"
    else info "$HOME/bin symlink already exists"
    fi
  else
      info "No current $HOME/bin folder found, starting symlink creation"
  fi
}

symlinks () {
  # symlink .dotfiles bin to ~
  ln -s $HOME/.dotfiles/bin $HOME/bin && ok "symlink for $HOME/bin folder created"

  # symlink .dotfiles tmux to ~
  ln -s $HOME/.dotfiles/tmux $HOME/.tmux && ok "symlink for $HOME/.tmux folder created"

  # symlink VSCode User Settings
  if [ -d $HOME/Library/Application\ Support/Code/User ] ; then
    running "Making backup of current settings.json and creating symlink..."
    mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.old.json && ok "settings.old.json created"
    ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json && ok "settings.json for vs code symlink created"
  else
    info "symlink for vs code settings not created"
    warn "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
  fi

  # airport symlink
  if ! [ -f /usr/local/bin/airport ]
    then
      sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport
      ok "symlink for airport created"
    else 
      info "symlink for airport already exists"
    fi
}

colors () {
  # colorls setup
  sudo gem install colorls
  sudo mkdir -p ~/.config/colorls && sudo cp ./dark_colors.yaml ~/.config/colorls/dark_colors.yaml
  ok 'ls colors have been configured'
}

crontab () {
  #crontab additions
  add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    if [[ $? -eq 0 ]]
    then
    ok "$PATH added to crontab"
    else
    info "ERROR $PATH could not be added to crontab"
    fi

  add_cron "speedtest-cli --simple > ~/bin/bandwidth.log"
    if [[ $? -eq 0 ]]
    then
    ok "crontab created for speedtest cli --simple"
    else
    info "ERROR crontab could not be created for speedtest cli --simple"
    fi

  add_cron "speedtest-cli --json > ~/bin/bandwidth.json"
    if [[ $? -eq 0 ]]
    then
    ok "crontab created for speedtest cli --json"
    else
    info "ERROR crontab could not be created for speedtest cli --json"
    fi

  # first run of speedtest-cli
  running "Running speedtest-cli for tmux status bar data now..."
  speedtest-cli --simple > ~/bin/bandwidth.log
  ok "speedtest-cli bandwidth.log created"

  speedtest-cli --json > ~/bin/bandwidth.json
  ok "speedtest-cli bandwidth.json created"
}

itermConfig () {
  # iterm2 config
  read -p "Do you currently use iTerm2 and would you like to set aaroncoville's custom colors? y/n " -n 1 -r
  echo ''
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    # Specify the preferences directory
    defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/.itermcfg/"
    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
      if [[ $? -eq 0 ]]
      then
          ok "okfully configured iTerm2 to use aaroncoville's custom colors..."
      else
          fail "failed to apply aaroncoville's custom colors..." >&2
  fi
  else 
      info "You chose not to use iTerm2 or aaroncoville's custom colors."
  fi
}

fontSetup () {
  # install Source Code Pro nerd font
  sudo cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
  ok "Source Code Pro font copied okfully!"
}

configFix () {
  # .config permissions fix
  if [ ! -d "$HOME/.config" ]; then
    info "$HOME/.config doesn't exist, nothing to fix"
  else
    sudo chown $(whoami) $HOME/.config 
    ok '.config permissions fixed'
  fi
}

setup_gitconfig
install_dotfiles

# If we're on a Mac, let's install and setup homebrew.
if [ "$(uname -s)" == "Darwin" ]
then
  info "installing dependencies"
  if source bin/dot | while read -r data; do info "$data"; done
  then
    ok "dependencies installed"
    echo ''
    running "Now updating dependencies..."
    pip3 install --upgrade setuptools
  else
    fail "error installing dependencies"
  fi
fi
installMods
symlinks
colors
#crontab
itermConfig
fontSetup
configFix

ok 'Badass macOS terminal installed!'